# Generated by Django 5.2.7 on 2025-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_fipe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="fipe_id",
        ),
        migrations.AddField(
            model_name="car",
            name="ano_codigo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="marca_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="modelo_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
