# Generated by Django 5.2.7 on 2025-10-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_fipe_id_car_ano_codigo_car_marca_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="fipe_price",
        ),
    ]
