# Generated by Django 5.2.7 on 2025-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                (
                    "store_type",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("rental", "Rental")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
