# Generated by Django 5.2.7 on 2025-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="cars",
            field=models.ManyToManyField(related_name="stores", to="cars.car"),
        ),
    ]
